/**
 * MVU Generator - generates MVU (Model-View-Update) five-piece set assets.
 * Based on world-book-mcp v5 methodology.
 *
 * Five files:
 *   1. schema.js     - Zod schema defining variable structure
 *   2. initvar.yaml  - Initial variable values
 *   3. update-rules.yaml - When/how variables update
 *   4. variable-list.md  - Variable documentation
 *   5. output-format.md  - AI output format for variable updates
 *
 * Also generates optional frontend beautification assets:
 *   - Status bar HTML/CSS
 *   - Story view beautification HTML
 *   - MVU update visualization HTML
 */
import type { MvuVariable, MvuConfig } from '../constants/defaults';

// ── Schema.js builder ─────────────────────────────────────────────────────

/**
 * Build schema.js content from MVU variables.
 * Uses Zod 4 syntax as per world-book-mcp v5 spec.
 */
export function buildSchemaJs(variables: MvuVariable[]): string {
  const lines = [
    '// Generated by Tavern Card Helper — MVU schema',
    '// Runtime provides z (Zod) and _ (lodash with .clamp)',
    'export const Schema = z.object({',
  ];

  const tree = buildVariableTree(variables);
  lines.push(...renderSchemaTree(tree, 1));
  lines.push('});', '');
  return lines.join('\n');
}

interface VariableTree {
  [key: string]: VariableTree | MvuVariable;
}

function buildVariableTree(variables: MvuVariable[]): VariableTree {
  const root: VariableTree = {};
  for (const v of variables) {
    let cursor = root;
    for (let i = 0; i < v.path.length; i++) {
      const seg = v.path[i];
      if (i === v.path.length - 1) {
        cursor[seg] = v;
      } else {
        if (!cursor[seg] || isMvuVariable(cursor[seg])) {
          cursor[seg] = {} as VariableTree;
        }
        cursor = cursor[seg] as VariableTree;
      }
    }
  }
  return root;
}

function isMvuVariable(value: unknown): value is MvuVariable {
  return typeof value === 'object' && value !== null && 'path' in value && Array.isArray((value as MvuVariable).path);
}

function renderSchemaTree(tree: VariableTree, depth: number): string[] {
  const indent = '  '.repeat(depth);
  const lines: string[] = [];
  for (const [key, value] of Object.entries(tree)) {
    if (isMvuVariable(value)) {
      lines.push(`${indent}${JSON.stringify(key)}: ${schemaExpression(value)},`);
    } else {
      lines.push(`${indent}${JSON.stringify(key)}: z.object({`);
      lines.push(...renderSchemaTree(value, depth + 1));
      lines.push(`${indent}}),`);
    }
  }
  return lines;
}

function schemaExpression(v: MvuVariable): string {
  switch (v.kind) {
    case 'number': {
      const hasRange = typeof v.min === 'number' || typeof v.max === 'number';
      const base = 'z.coerce.number()';
      if (hasRange) {
        return `${base}.transform(v => _.clamp(v, ${v.min ?? '-Infinity'}, ${v.max ?? 'Infinity'}))`;
      }
      return base;
    }
    case 'boolean':
      return 'z.boolean()';
    case 'enum':
      if (v.enumValues && v.enumValues.length > 0) {
        return `z.enum([${v.enumValues.map(e => JSON.stringify(e)).join(', ')}])`;
      }
      return 'z.string()';
    case 'record':
      return 'z.record(z.string(), z.unknown())';
    case 'object':
      return 'z.object({})';
    default:
      return 'z.string()';
  }
}

// ── initvar.yaml builder ──────────────────────────────────────────────────

/**
 * Build initvar.yaml content from MVU variables.
 * Generates nested YAML structure with default values.
 */
export function buildInitvarYaml(variables: MvuVariable[]): string {
  const root: Record<string, unknown> = {};
  for (const v of variables) {
    setNested(root, v.path, v.defaultValue ?? defaultForKind(v.kind));
  }
  return yamlStringify(root) + '\n';
}

// ── update-rules.yaml builder ─────────────────────────────────────────────

/**
 * Build update-rules.yaml content from MVU variables.
 * Skips hidden (_) and readonly ($) variables per spec.
 */
export function buildUpdateRules(variables: MvuVariable[]): string {
  const rules: Record<string, unknown> = {};
  for (const v of variables) {
    if (shouldSkipUpdateRule(v)) continue;
    const rule: Record<string, unknown> = {};

    if (v.kind === 'number') {
      rule.type = 'number';
      if (typeof v.min === 'number' || typeof v.max === 'number') {
        rule.range = `${v.min ?? '-Infinity'}~${v.max ?? 'Infinity'}`;
      }
    } else if (v.kind === 'boolean') {
      rule.type = 'boolean';
    } else if (v.kind === 'enum' && v.enumValues?.length) {
      rule.type = v.enumValues.map(e => `'${e}'`).join('|');
    } else if (v.kind === 'record') {
      rule.type = '{ [key: string]: unknown }';
    }

    if (v.description) rule.value = v.description;
    if (Object.keys(rule).length > 0) setNested(rules, v.path, rule);
  }
  return yamlStringify({ 变量更新规则: rules });
}

function shouldSkipUpdateRule(v: MvuVariable): boolean {
  const last = v.path.at(-1) ?? '';
  return Boolean(
    v.readonly || v.hidden ||
    last.startsWith('_') || last.startsWith('$') ||
    v.path.some(seg => seg.startsWith('_') || seg.startsWith('$'))
  );
}

// ── variable-list.md builder ──────────────────────────────────────────────

/**
 * Build variable-list.md content.
 * Standard format with current variables block and descriptions.
 */
export function buildVariableList(variables: MvuVariable[]): string {
  const descriptions = variables
    .map(v => {
      const dotPath = v.path.join('.');
      return `- stat_data.${dotPath}${v.description ? `：${v.description}` : ''}`;
    })
    .join('\n');

  return [
    '---',
    '<status_current_variables>',
    '{{format_message_variable::stat_data}}',
    '</status_current_variables>',
    '',
    '# 变量说明',
    descriptions,
    '',
  ].join('\n');
}

// ── output-format.md builder ──────────────────────────────────────────────

/**
 * Build output-format.md content.
 * Defines how AI should output variable updates using JSON Patch format.
 */
export function buildOutputFormat(variables: MvuVariable[]): string {
  const examples = variables
    .filter(v => !shouldSkipUpdateRule(v))
    .map(v => {
      const path = '/' + v.path.join('/');
      const value = JSON.stringify(v.defaultValue ?? defaultForKind(v.kind));
      return `      { "op": "replace", "path": "${path}", "value": ${value} }`;
    })
    .join(',\n');

  const trackedVars = variables
    .map(v => `    - stat_data.${v.path.join('.')}`)
    .join('\n');

  return [
    '---',
    '变量输出格式:',
    '  rule:',
    '    - 在下一次回复末尾同时输出更新分析和实际更新命令。',
    '    - 更新命令必须是 JSON Patch 风格的 JSON 数组；路径不带 stat_data 根键。',
    '    - 支持 replace、delta、insert、remove、move；不要更新字段名以 _ 或 $ 开头的变量。',
    '  tracked_variables:',
    trackedVars,
    '  format: |-',
    '    <UpdateVariable>',
    '    <Analysis>$(IN ENGLISH, no more than 80 words; analyze only the current reply.)</Analysis>',
    '    <JSONPatch>',
    '    [',
    examples || '      { "op": "replace", "path": "/变量路径", "value": "新值" }',
    '    ]',
    '    </JSONPatch>',
    '    </UpdateVariable>',
    '',
  ].join('\n');
}

// ── Status bar HTML/CSS builder ───────────────────────────────────────────

/**
 * Generate status bar HTML based on MVU variables.
 * Uses safe_macro mode with format_message_variable.
 */
export function buildStatusBarHtml(variables: MvuVariable[], mode: 'safe_macro' | 'dynamic_js'): string {
  // Filter to displayable variables (not hidden, not readonly internal)
  const displayVars = variables.filter(v => !v.hidden && !v.path.some(s => s.startsWith('$')));

  if (mode === 'dynamic_js') {
    return buildDynamicStatusBarHtml(displayVars);
  }

  // safe_macro mode
  const rows = displayVars.map(v => {
    const dotPath = `stat_data.${v.path.join('.')}`;
    const label = v.path.at(-1) ?? v.path.join('.');
    return `    <div class="status-row">
      <span class="status-label">${label}</span>
      <strong class="status-value">{{format_message_variable::${dotPath}}}</strong>
    </div>`;
  }).join('\n');

  return `<div class="mvu-status-card">
  <div class="status-header">状态面板</div>
${rows}
</div>`;
}

function buildDynamicStatusBarHtml(variables: MvuVariable[]): string {
  const ids = variables.map(v => ({
    id: `mvu-${v.path.join('-')}`,
    label: v.path.at(-1) ?? v.path.join('.'),
    jsPath: v.path.join('.'),
    defaultVal: v.defaultValue ?? defaultForKind(v.kind),
  }));

  const rows = ids.map(item =>
    `    <div class="status-row">
      <span class="status-label">${item.label}</span>
      <strong class="status-value" id="${item.id}">${String(item.defaultVal)}</strong>
    </div>`
  ).join('\n');

  const updates = ids.map(item =>
    `      $('#${item.id}').text(_.get(statData, '${item.jsPath}', '${item.defaultVal}'));`
  ).join('\n');

  return `<!doctype html>
<html lang="zh-CN">
<head>
  <style>
  .mvu-status-card {
    width: 92%; margin: 12px auto; padding: 12px 14px;
    border: 1px solid rgba(148, 163, 184, .28); border-radius: 14px;
    background: rgba(15, 23, 42, .72); color: #e2e8f0;
  }
  .status-header { font-size: 13px; font-weight: 600; margin-bottom: 8px; opacity: .7; }
  .status-row { display: flex; justify-content: space-between; gap: 12px; padding: 4px 0; }
  .status-label { font-size: 12px; color: #94a3b8; }
  .status-value { font-size: 13px; color: #e2e8f0; }
  </style>
  <script type="module">
    async function initStatusBar() {
      await waitGlobalInitialized('Mvu');
      function render() {
        const allVariables = getAllVariables();
        const statData = _.get(allVariables, 'stat_data', {});
${updates}
      }
      render();
      if (typeof Mvu !== 'undefined' && Mvu.events) {
        eventOn(Mvu.events.VARIABLE_UPDATE_ENDED, render);
      }
    }
    $(errorCatched(initStatusBar));
  </script>
</head>
<body>
  <div class="mvu-status-card">
    <div class="status-header">状态面板</div>
${rows}
  </div>
</body>
</html>`;
}

/**
 * Generate status bar CSS for safe_macro mode.
 */
export function buildStatusBarCss(): string {
  return `.mvu-status-card {
  width: 92%;
  margin: 12px auto;
  padding: 12px 14px;
  border: 1px solid rgba(148, 163, 184, .28);
  border-radius: 14px;
  background: rgba(15, 23, 42, .72);
  color: #e2e8f0;
}
.status-header {
  font-size: 13px;
  font-weight: 600;
  margin-bottom: 8px;
  opacity: .7;
}
.status-row {
  display: flex;
  justify-content: space-between;
  gap: 12px;
  padding: 4px 0;
}
.status-label {
  font-size: 12px;
  color: #94a3b8;
}
.status-value {
  font-size: 13px;
  color: #e2e8f0;
}`;
}

// ── Story beautification HTML builder ──────────────────────────────────────

/**
 * Generate story view beautification HTML.
 * Replaces content within custom tags with styled HTML.
 */
export function buildStoryBeautifyHtml(tag: string): string {
  return `<!-- Story view beautification for <${tag}> -->
<div class="story-view-container">
  <div class="story-view-content" id="story-content"></div>
</div>
<style>
  .story-view-container {
    width: 92%;
    margin: 12px auto;
    padding: 16px 18px;
    border: 1px solid rgba(148, 163, 184, .18);
    border-radius: 14px;
    background: linear-gradient(135deg, rgba(15, 23, 42, .6) 0%, rgba(30, 41, 59, .4) 100%);
    color: #cbd5e1;
    line-height: 1.75;
  }
  .story-view-content {
    font-size: 14px;
    white-space: pre-wrap;
  }
  .story-view-content p {
    margin: 0.5em 0;
  }
</style>
<script type="module">
  /* Parse the current message for <${tag}> content and render */
  try {
    const mesText = document.currentScript?.closest('.mes_text');
    if (mesText) {
      const match = mesText.innerHTML.match(/<${tag}>([\\s\\S]*?)<\\/${tag}>/);
      if (match) {
        const el = document.getElementById('story-content');
        if (el) el.innerHTML = match[1].trim();
      }
    }
  } catch(e) { /* graceful fallback */ }
</script>`;
}

// ── MVU update beautification HTML ────────────────────────────────────────

/**
 * Generate MVU update loading beautification HTML.
 * Shows a shimmer loading state while variables are being updated.
 */
export function buildMvuLoadingBeautifyHtml(): string {
  return `<div style="width: 82%; margin: 18px auto;">
  <details class="mvu-loading-details" style="background:linear-gradient(135deg,#0f172a 0%,#1e293b 52%,#0f172a 100%);border:1px solid rgba(148,163,184,.22);border-radius:16px;box-shadow:0 4px 22px rgba(96,165,250,.16),inset 0 1px 0 rgba(148,163,184,.1);overflow:hidden;">
    <summary style="padding:14px 20px;color:#e2e8f0;cursor:pointer;list-style:none;position:relative;overflow:hidden;display:flex;align-items:center;gap:10px;font-weight:500;">
      <span style="filter:drop-shadow(0 0 8px rgba(125,211,252,.8));">✦</span><span style="flex:1;">变量更新中</span><small style="opacity:.72;">正在整理状态</small><span style="position:absolute;top:0;left:0;width:100%;height:100%;background:linear-gradient(90deg,transparent,rgba(186,230,253,.12),transparent);animation:mvuShimmer 2s linear infinite;transform:translateX(-100%);pointer-events:none;"></span>
    </summary>
    <div style="max-height:300px;overflow-y:auto;padding:14px 20px;color:#cbd5e1;line-height:1.65;white-space:pre-wrap;background:rgba(15,23,42,.32);">$2</div>
  </details>
</div>
<style>@keyframes mvuShimmer{100%{transform:translateX(100%)}}</style>`;
}

/**
 * Generate MVU update done beautification HTML.
 * Shows a collapsible panel with the update analysis.
 */
export function buildMvuDoneBeautifyHtml(): string {
  return `<div style="width: 82%; margin: 18px auto;">
  <details class="mvu-thinking-description" style="background:linear-gradient(135deg,#0f172a 0%,#1e293b 52%,#0f172a 100%);border:1px solid rgba(148,163,184,.22);border-radius:16px;box-shadow:0 4px 22px rgba(56,189,248,.14),inset 0 1px 0 rgba(148,163,184,.1);overflow:hidden;">
    <summary style="padding:14px 20px;color:#e2e8f0;cursor:pointer;list-style:none;font-weight:500;display:flex;align-items:center;gap:10px;"><span style="filter:drop-shadow(0 0 8px rgba(56,189,248,.72));">◈</span><span style="flex:1;">变量更新</span><small style="opacity:.72;">点击查看/隐藏</small></summary>
    <div style="max-height:300px;overflow-y:auto;padding:14px 20px;color:#cbd5e1;line-height:1.65;white-space:pre-wrap;background:rgba(15,23,42,.32);">$2</div>
  </details>
</div>`;
}

// ── Full MVU asset generation ────────────────────────────────────────────

/**
 * Generate all MVU assets from an MvuConfig.
 * Returns the updated config with generated asset text populated.
 */
export function generateAllMvuAssets(config: MvuConfig): MvuConfig {
  if (!config.enabled || config.variables.length === 0) return config;

  return {
    ...config,
    schemaJs: buildSchemaJs(config.variables),
    initvarYaml: buildInitvarYaml(config.variables),
    updateRulesYaml: buildUpdateRules(config.variables),
    variableListMd: buildVariableList(config.variables),
    outputFormatMd: buildOutputFormat(config.variables),
    // Generate status bar if enabled
    statusBarHtml: config.statusBarEnabled
      ? buildStatusBarHtml(config.variables, config.statusBarMode)
      : config.statusBarHtml,
    statusBarCss: config.statusBarEnabled && config.statusBarMode === 'safe_macro'
      ? buildStatusBarCss()
      : config.statusBarCss,
    // Generate story beautification if enabled
    storyBeautifyHtml: config.storyBeautifyEnabled
      ? buildStoryBeautifyHtml(config.storyBeautifyTag || 'story_view')
      : config.storyBeautifyHtml,
  };
}

/**
 * Package all MVU assets as downloadable files.
 * Returns an array of { filename, content } pairs.
 */
export function packageMvuAssets(config: MvuConfig): Array<{ filename: string; content: string }> {
  const files: Array<{ filename: string; content: string }> = [];

  if (config.enabled && config.variables.length > 0) {
    files.push({ filename: 'mvu/schema.js', content: config.schemaJs });
    files.push({ filename: 'mvu/initvar.yaml', content: config.initvarYaml });
    files.push({ filename: 'mvu/update-rules.yaml', content: config.updateRulesYaml });
    files.push({ filename: 'mvu/variable-list.md', content: config.variableListMd });
    files.push({ filename: 'mvu/output-format.md', content: config.outputFormatMd });
  }

  if (config.statusBarEnabled) {
    if (config.statusBarMode === 'safe_macro') {
      files.push({ filename: 'html/statusbar.html', content: config.statusBarHtml });
      files.push({ filename: 'html/statusbar.css', content: config.statusBarCss });
    } else {
      files.push({ filename: 'html/statusbar.html', content: config.statusBarHtml });
    }
  }

  if (config.storyBeautifyEnabled && config.storyBeautifyHtml) {
    files.push({ filename: `html/${config.storyBeautifyTag || 'story-view'}.html`, content: config.storyBeautifyHtml });
  }

  // Always include MVU update beautification when MVU is enabled
  if (config.enabled && config.variables.length > 0) {
    files.push({ filename: 'html/变量更新中美化.html', content: buildMvuLoadingBeautifyHtml() });
    files.push({ filename: 'html/变量更新美化.html', content: buildMvuDoneBeautifyHtml() });
  }

  return files;
}

/**
 * Download all MVU assets as individual files.
 */
export function downloadMvuAssets(config: MvuConfig): void {
  const files = packageMvuAssets(config);
  if (files.length === 0) return;

  // Create a simple text bundle for convenience
  const bundle = files.map(f => `// ═══ ${f.filename} ═══\n${f.content}`).join('\n\n');
  const blob = new Blob([bundle], { type: 'text/plain;charset=utf-8' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = 'mvu-assets.txt';
  a.click();
  URL.revokeObjectURL(url);
}

// ── Utility helpers ───────────────────────────────────────────────────────

function defaultForKind(kind?: string): unknown {
  if (kind === 'number') return 0;
  if (kind === 'boolean') return false;
  if (kind === 'object' || kind === 'record') return {};
  return '';
}

function setNested(root: Record<string, unknown>, segments: string[], value: unknown): void {
  let cursor = root;
  for (let i = 0; i < segments.length; i++) {
    if (i === segments.length - 1) {
      cursor[segments[i]] = value;
    } else {
      const existing = cursor[segments[i]];
      if (!existing || typeof existing !== 'object') {
        cursor[segments[i]] = {};
      }
      cursor = cursor[segments[i]] as Record<string, unknown>;
    }
  }
}

/** Simple YAML stringifier for nested objects */
function yamlStringify(obj: Record<string, unknown>, indent = 0): string {
  const prefix = '  '.repeat(indent);
  const lines: string[] = [];
  for (const [key, value] of Object.entries(obj)) {
    if (value === null || value === undefined) {
      lines.push(`${prefix}${key}: null`);
    } else if (typeof value === 'object' && !Array.isArray(value)) {
      lines.push(`${prefix}${key}:`);
      lines.push(yamlStringify(value as Record<string, unknown>, indent + 1));
    } else if (Array.isArray(value)) {
      lines.push(`${prefix}${key}:`);
      for (const item of value) {
        lines.push(`${prefix}  - ${yamlScalar(item)}`);
      }
    } else {
      lines.push(`${prefix}${key}: ${yamlScalar(value)}`);
    }
  }
  return lines.join('\n');
}

function yamlScalar(value: unknown): string {
  if (typeof value === 'string') {
    // Quote strings that could be misinterpreted
    if (/^(true|false|null|yes|no|on|off|\d)/i.test(value) || value.includes(':') || value.includes('#') || value.includes('\n')) {
      return `"${value.replace(/"/g, '\\"')}"`;
    }
    return value;
  }
  return String(value);
}
